<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="FAQ.aspx.cs" Inherits="FAQ" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


<div id ="wrapper">

<h1>Frequently Asked Questions</h1>

<h2>1. What does this software do?</h2>

<p1> This application compares how the Hard Drive is meant to be performing against how it is actually performing! This
comparison allows the user to identify potential problems and innificenies within the hard drive. By utilising the phDD application
 the user can determine the route to extract the optimum performance out of their harddrive. As well as performance analysis the phDD 
 application identifies in colour coding how well the Hard Drive is performing.
 
 
 
  </p1>

<h2>2. Does this software pose any risk to my computer?</h2>

<p1>A simple answer.....No. The phDD software is only reading from your HardDrive. There is no writing or manipulation of perssions. In terms of confidentiality
    there are no Issues. phDD can only access the information required to read the HDD and no more. We have no access to any personal information!</p1>

<h2>3. How do I run the PhdD software?</h2>

<p1>Click on the Download tab on the Website Menu. Once the download page opens up you will be able to download the phDD application. Simples!</p1>

<h2>4. How accurate are the results from the Hard Drive Analysis?</h2>

<p1> The results generated by the phDD application are 100% accurate and are displayed in real time which means that the HDD information being displayed
     is exactly how the Hard Drive is currently performing and any changes are being updated live.</p1>

<h2>5. How is it possible for James to be so Handsome and talented?</h2>

<p1>People say it is impossible to be so perfect but he has proved the world wrong.</p1>




</div>
</asp:Content>

